In [3]:
sc
import pandas as pd

In [4]:
bdata = pd.read_csv('/nfs/science/shared/ipythonNotebooks/garimaj/McDonalds/nmf_base_data.csv',header=0, delimiter=",")
df=bdata.groupby(['trans_key','item_name'])['units'].max().unstack()

print df.shape

(1033222, 749)

In [5]:
import numpy as np

X = df.as_matrix()
print X.view()

where_are_NaNs = np.isnan(X)
X[where_are_NaNs] = 0
print X.view()
print X.shape

[[ nan  nan  nan ...,  nan  nan   0.]
 [ nan  nan  nan ...,  nan  nan   0.]
 [ nan  nan  nan ...,  nan  nan   0.]
 ...,
 [ nan  nan  nan ...,  nan  nan   0.]
 [ nan  nan  nan ...,  nan  nan   0.]
 [ nan  nan  nan ...,  nan  nan   0.]]
[[ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 ...,
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]]
(1033222, 749)

## Run 1

In [ ]:
from sklearn.decomposition import NMF
import time

start_time=time.time()

c=5  
    
print("Fitting the NMF model for %d features" %(c) )
nmf = NMF(n_components=c, beta_loss='kullback-leibler',random_state=12, alpha=0.1,verbose =2, max_iter=300,
          l1_ratio=0.5,init = 'nndsvda', solver='mu')
nmf.fit(X)

time_taken=time.time()-start_time
minutes, seconds=divmod(time_taken,60)
print("Time taken to complete: %d minutes, %d seconds" %(minutes,seconds))

print "Error: %d" %(nmf.reconstruction_err_)
print "Iterations: %d" %(nmf.n_iter_)

start_time=time.time()

c=6
    
print("Fitting the NMF model for %d features" %(c) )
nmf6 = NMF(n_components=c, beta_loss='kullback-leibler',random_state=12, alpha=0.1,verbose =2, max_iter=300,
          l1_ratio=0.5,init = 'nndsvda', solver='mu')
nmf6.fit(X)

time_taken=time.time()-start_time
minutes, seconds=divmod(time_taken,60)
print("Time taken to complete: %d minutes, %d seconds" %(minutes,seconds))

print "Error: %d" %(nmf6.reconstruction_err_)
print "Iterations: %d" %(nmf6.n_iter_)

c=7
    
print("Fitting the NMF model for %d features" %(c) )
nmf7 = NMF(n_components=c, beta_loss='kullback-leibler',random_state=12, alpha=0.1,verbose =2, max_iter=300,
          l1_ratio=0.5,init = 'nndsvda', solver='mu')
nmf7.fit(X)

time_taken=time.time()-start_time
minutes, seconds=divmod(time_taken,60)
print("Time taken to complete: %d minutes, %d seconds" %(minutes,seconds))

print "Error: %d" %(nmf7.reconstruction_err_)
print "Iterations: %d" %(nmf7.n_iter_)

c=8
    
print("Fitting the NMF model for %d features" %(c) )
nmf8 = NMF(n_components=c, beta_loss='kullback-leibler',random_state=12, alpha=0.1,verbose =2, max_iter=300,
          l1_ratio=0.5,init = 'nndsvda', solver='mu')
nmf8.fit(X)

time_taken=time.time()-start_time
minutes, seconds=divmod(time_taken,60)
print("Time taken to complete: %d minutes, %d seconds" %(minutes,seconds))

print "Error: %d" %(nmf8.reconstruction_err_)
print "Iterations: %d" %(nmf8.n_iter_)

Fitting the NMF model for 5 features
Epoch 10 reached after 330.641 seconds, error: 3873.052306
Epoch 20 reached after 662.154 seconds, error: 3864.289491
Epoch 30 reached after 1015.679 seconds, error: 3862.842175
Epoch 40 reached after 1392.318 seconds, error: 3861.525853
Epoch 50 reached after 1787.503 seconds, error: 3861.086603
Time taken to complete: 31 minutes, 38 seconds
Error: 3861
Iterations: 50
Fitting the NMF model for 6 features
Epoch 10 reached after 311.896 seconds, error: 3806.874786
Epoch 20 reached after 623.499 seconds, error: 3797.690179
Epoch 30 reached after 958.798 seconds, error: 3794.509247
Epoch 40 reached after 1307.722 seconds, error: 3792.835953
Epoch 50 reached after 1648.201 seconds, error: 3792.142586
Epoch 60 reached after 1989.511 seconds, error: 3791.637912
Epoch 70 reached after 2373.338 seconds, error: 3790.665013
Epoch 80 reached after 2716.736 seconds, error: 3790.170344
Epoch 90 reached after 3053.743 seconds, error: 3790.003300
Time taken to complete: 52 minutes, 10 seconds
Error: 3790
Iterations: 90
Fitting the NMF model for 7 features
Epoch 10 reached after 323.383 seconds, error: 3705.925554
Epoch 20 reached after 657.597 seconds, error: 3697.287476
Epoch 30 reached after 1029.525 seconds, error: 3694.696661
Epoch 40 reached after 1420.299 seconds, error: 3693.740817
Epoch 50 reached after 1877.924 seconds, error: 3692.914682
Epoch 60 reached after 2313.849 seconds, error: 3692.317203
Epoch 70 reached after 2742.984 seconds, error: 3692.264096
Time taken to complete: 99 minutes, 56 seconds
Error: 3692
Iterations: 70
Fitting the NMF model for 8 features

In [7]:
print "Error: %d" %(nmf8.reconstruction_err_)

Error: 3608

In [8]:
c=9    
print("Fitting the NMF model for %d features" %(c) )
nmf9 = NMF(n_components=c, beta_loss='kullback-leibler',random_state=12, alpha=0.1,verbose =2, tol=1.0, max_iter=60,
          l1_ratio=0.5,init = 'nndsvda', solver='mu')
nmf9.fit(X)
print "Error: %d" %(nmf9.reconstruction_err_)

c=10    
print("Fitting the NMF model for %d features" %(c) )
nmf10 = NMF(n_components=c, beta_loss='kullback-leibler',random_state=12, alpha=0.1,verbose =2, tol=1.0, max_iter=60,
          l1_ratio=0.5,init = 'nndsvda', solver='mu')
nmf10.fit(X)
print "Error: %d" %(nmf10.reconstruction_err_)

c=11    
print("Fitting the NMF model for %d features" %(c) )
nmf11 = NMF(n_components=c, beta_loss='kullback-leibler',random_state=12, alpha=0.1,verbose =2, tol=1.0, max_iter=60,
          l1_ratio=0.5,init = 'nndsvda', solver='mu')
nmf11.fit(X)
print "Error: %d" %(nmf11.reconstruction_err_)

Fitting the NMF model for 9 features
Epoch 10 reached after 367.737 seconds, error: 3562.207484
Error: 3562
Fitting the NMF model for 10 features
Epoch 10 reached after 339.867 seconds, error: 3497.632264
Error: 3497
Fitting the NMF model for 11 features
Epoch 10 reached after 389.208 seconds, error: 3425.893725
Error: 3425

In [9]:
c=12   
print("Fitting the NMF model for %d features" %(c) )
nmf12 = NMF(n_components=c, beta_loss='kullback-leibler',random_state=12, alpha=0.1,verbose =2, tol=1.0, max_iter=60,
          l1_ratio=0.5,init = 'nndsvda', solver='mu')
nmf12.fit(X)
print "Error: %d" %(nmf12.reconstruction_err_)

c=13 
print("Fitting the NMF model for %d features" %(c) )
nmf13 = NMF(n_components=c, beta_loss='kullback-leibler',random_state=12, alpha=0.1,verbose =2, tol=1.0, max_iter=60,
          l1_ratio=0.5,init = 'nndsvda', solver='mu')
nmf13.fit(X)
print "Error: %d" %(nmf13.reconstruction_err_)

c=14    
print("Fitting the NMF model for %d features" %(c) )
nmf14= NMF(n_components=c, beta_loss='kullback-leibler',random_state=12, alpha=0.1,verbose =2, tol=1.0, max_iter=60,
          l1_ratio=0.5,init = 'nndsvda', solver='mu')
nmf14.fit(X)
print "Error: %d" %(nmf14.reconstruction_err_)

Fitting the NMF model for 12 features
Epoch 10 reached after 339.893 seconds, error: 3363.073816
Error: 3363
Fitting the NMF model for 13 features
Epoch 10 reached after 395.200 seconds, error: 3311.844777
Error: 3311
Fitting the NMF model for 14 features
Epoch 10 reached after 359.348 seconds, error: 3260.555752
Error: 3260

In [10]:
c=12   
print("Fitting the NMF model for %d features" %(c) )
nmf12 = NMF(n_components=c, beta_loss='kullback-leibler',random_state=12, alpha=0.1,verbose =2, tol=0.001, max_iter=150,
          l1_ratio=0.5,init = 'nndsvda', solver='mu')
nmf12.fit(X)
print "Error: %d" %(nmf12.reconstruction_err_)

Fitting the NMF model for 12 features
Epoch 10 reached after 355.411 seconds, error: 3363.073816
Epoch 20 reached after 721.988 seconds, error: 3350.304217
Epoch 30 reached after 1120.941 seconds, error: 3349.768779
Error: 3349

In [11]:
#load a stored model
from sklearn.externals import joblib
joblib.dump(nmf12, 'mcd_missions.pkl', compress=9)
# classifier=joblib.load('na_model.pkl')

['mcd_missions.pkl']

In [14]:
# Missions X Products matrix
Y = pd.DataFrame(nmf12.components_, columns=df.columns) #[n_components, n_features]
Y.head(15)

item_name,1 COOKIE,1 FULL STRIP BACON,1/2 CRISPY CKN,1/4 LB BEEF,10 MCNUGGETS,10 MCNUGGETS MEAL,10 MCNUGGETS ML-HB,10 MCNUGGETS ML-LRG,10 MCNUGGETS ML-SLD,10 Pc Chicken Tender,...,XS DR. PEPPER,XS FANTA STRAWBERRY,XS FOUNTAIN DRINK,XS Fanta Orange,XS HI-C ORANGE,XS LEMONADE,XS SPRITE,XS SWEET ICED TEA,XS UNSWEET ICED TEA,custom_meal
0,0.00000,0.000000,0.00000,0.000000,2.395041e-09,0.000000,0.000000,2.410154e+00,0.000000,0.000000e+00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,9.280235e-01
1,0.00000,0.000000,0.00000,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,7.293032e-15
2,0.00000,0.000000,0.00000,0.000000,8.610966e-15,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,...,0.000000,0.000000,0.002934,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,2.473615e-02
3,0.00000,0.000000,0.00000,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,3.515376e-13
4,0.00000,0.000000,0.00000,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,7.709230e-01
5,0.00000,0.000388,0.00000,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.004458,3.372510e-02,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,5.433958e-12
6,0.00000,0.000000,0.00166,0.000000,4.778413e-12,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00
7,0.00000,0.000000,0.00000,0.000000,3.812128e+00,0.000000,0.000000,0.000000e+00,0.000000,2.906815e-16,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,5.394216e+00
8,1.60523,0.000000,0.00000,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,...,0.000000,0.000000,0.000000,0.000000,0.000000,2.167788e-12,0.000000,0.000000,0.000000,2.415538e+00
9,0.00000,0.000000,0.00000,0.139509,0.000000e+00,0.000000,0.000634,0.000000e+00,0.000000,0.000000e+00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00
10,0.00000,0.000000,0.00000,0.000000,3.150834e-15,2.733697,0.000000,3.183394e-10,0.000000,0.000000e+00,...,0.028295,0.001035,0.000000,0.022084,0.007936,3.657667e-02,0.085231,0.009834,0.009144,0.000000e+00
11,0.00000,0.000000,0.00000,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,1.312801e-03

In [26]:
Y.iloc[11].nlargest(20)

item_name
VANILLA CONE            12.221792
HOT FUDGE SUNDAE         4.609743
OREO MCFLURRY            4.519928
M&M MCFLURRY             1.427267
CARAMEL SUNDAE           1.387957
STRAWBERRY SUNDAE        0.832560
ROLO MCFLURRY            0.753718
PLAIN SUNDAE             0.407168
FUDGE TOPPING            0.284622
MCDOUBLE MEAL            0.260904
OREO TOPPING             0.173277
GRL CHICKEN PATTY        0.164493
CPY CKN BCNRAN SLD       0.155269
SWBBQ ART-CPY ML-LRG     0.130233
M&M TOPPING              0.122107
PICO GUAC SSM-GRL        0.117056
CARAMEL TOPPING          0.113981
MCDOUBLE ML-LRG          0.106823
SIG SRACH ART-CPY ML     0.090921
SWT BBQ SSM-QTR MEAL     0.089604
Name: 11, dtype: float64

In [41]:
# Baskets X Missions matrix
bask_tag_12=nmf12.transform(X) #(n_samples, n_components)
bask_tag_12.shape

(1033222, 12)

In [44]:
bask_tg_12=pd.DataFrame(bask_tag_12)
bask_tg_12.index=df.index
bask_tg_12.head()

,0,1,2,3,4,5,6,7,8,9,10,11
trans_key,,,,,,,,,,,,
195500219028POS0001:306452907,0.000000,1.616851e-02,0.000000e+00,0.014654,0.0,0.0,0.000000,0.000000e+00,0.000000e+00,2.440706e-303,0.000000,0.0
195500219028POS0001:306452911,0.000000,3.277940e-211,0.000000e+00,0.014654,0.0,0.0,0.000000,0.000000e+00,1.893515e-02,0.000000e+00,0.000000,0.0
195500219028POS0001:306452917,0.000000,5.608538e-254,0.000000e+00,0.029308,0.0,0.0,0.000000,0.000000e+00,0.000000e+00,4.656190e-309,0.000000,0.0
195500219028POS0001:306452930,0.015176,0.000000e+00,4.114661e-301,0.000000,0.0,0.0,0.028617,1.310362e-02,5.035645e-191,0.000000e+00,0.000000,0.0
195500219028POS0001:306452955,0.015176,0.000000e+00,1.646800e-290,0.000000,0.0,0.0,0.000000,9.785924e-316,1.432790e-322,0.000000e+00,0.018923,0.0

In [84]:
# pd.set_option('display.float_format', lambda x: '%.5f' % x)
del bask_tg_12['max']
del bask_tg_12['max_2']

tagging=pd.DataFrame()
tagging['max']=bask_tg_12.apply(lambda x: bask_tg_12.columns[x.argsort()[::-1][11]], axis=1)
tagging['max_2']=bask_tg_12.apply(lambda x: bask_tg_12.columns[x.argsort()[::-1][10]], axis=1)
tagging.head(20)

                                       max  max_2
trans_key
195500219028POS0001:306452907            1      3
195500219028POS0001:306452911            8      3
195500219028POS0001:306452917            3      1
195500219028POS0001:306452930            6      0
195500219028POS0001:306452955           10      0
195500219028POS0001:306452956           10      2
195500219028POS0001:306452957           10     11
195500219028POS0001:306452981            0      7
195500219028POS0001:306452982            7     11
195500219028POS0001:306452989           10     11
195500219028POS0001:306452999            0      7
195500219028POS0001:306453018            3      1
195500219028POS0001:306453020            3      1
195500219028POS0001:306453037            5      3
195500219028POS0001:306453039            6      3
195500219028POS0001:306453051            8     11
195500219028POS0001:306453055            3      1
195500219028POS0001:306453064            9      6
195500219028POS0001:306453082            1      0
195500219028POS0001:306453083            1     11

In [90]:
bask_tg_12=bask_tg_12.merge(tagging, how='left', left_index=True, right_index=True, sort=False, suffixes=('_x', '_y'), copy=False)
bask_tg_12.head()

,0,1,2,3,4,5,6,7,8,9,10,11,max,max_2
trans_key,,,,,,,,,,,,,,
195500219028POS0001:306452907,0.00000,0.01617,0.00000,0.01465,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,1,3
195500219028POS0001:306452911,0.00000,0.00000,0.00000,0.01465,0.00000,0.00000,0.00000,0.00000,0.01894,0.00000,0.00000,0.00000,8,3
195500219028POS0001:306452917,0.00000,0.00000,0.00000,0.02931,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,3,1
195500219028POS0001:306452930,0.01518,0.00000,0.00000,0.00000,0.00000,0.00000,0.02862,0.01310,0.00000,0.00000,0.00000,0.00000,6,0
195500219028POS0001:306452955,0.01518,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.01892,0.00000,10,0

In [97]:
mis_check=bask_tg_12.groupby(['max','max_2']).count()
mis_check.to_csv('/nfs/science/shared/ipythonNotebooks/garimaj/McDonalds/mis_check.csv',header=0)
mis_check

              0      1      2      3      4      5      6      7      8   \
max max_2
0   1        783    783    783    783    783    783    783    783    783
    2       3308   3308   3308   3308   3308   3308   3308   3308   3308
    3       3129   3129   3129   3129   3129   3129   3129   3129   3129
    4       5718   5718   5718   5718   5718   5718   5718   5718   5718
    5        427    427    427    427    427    427    427    427    427
    6       3268   3268   3268   3268   3268   3268   3268   3268   3268
    7      22044  22044  22044  22044  22044  22044  22044  22044  22044
    8       3825   3825   3825   3825   3825   3825   3825   3825   3825
    9        153    153    153    153    153    153    153    153    153
    10      5579   5579   5579   5579   5579   5579   5579   5579   5579
    11      8381   8381   8381   8381   8381   8381   8381   8381   8381
1   0       7891   7891   7891   7891   7891   7891   7891   7891   7891
    2        135    135    135    135    135    135    135    135    135
    3      34523  34523  34523  34523  34523  34523  34523  34523  34523
    4        760    760    760    760    760    760    760    760    760
    5       2157   2157   2157   2157   2157   2157   2157   2157   2157
    6        813    813    813    813    813    813    813    813    813
    7       5813   5813   5813   5813   5813   5813   5813   5813   5813
    8       1174   1174   1174   1174   1174   1174   1174   1174   1174
    9        271    271    271    271    271    271    271    271    271
    10       702    702    702    702    702    702    702    702    702
    11     40445  40445  40445  40445  40445  40445  40445  40445  40445
2   0       5044   5044   5044   5044   5044   5044   5044   5044   5044
    1        785    785    785    785    785    785    785    785    785
    3        473    473    473    473    473    473    473    473    473
    4       1500   1500   1500   1500   1500   1500   1500   1500   1500
    5        574    574    574    574    574    574    574    574    574
    6       4413   4413   4413   4413   4413   4413   4413   4413   4413
    7       5820   5820   5820   5820   5820   5820   5820   5820   5820
    8       7770   7770   7770   7770   7770   7770   7770   7770   7770
...          ...    ...    ...    ...    ...    ...    ...    ...    ...
9   3      11727  11727  11727  11727  11727  11727  11727  11727  11727
    4       2756   2756   2756   2756   2756   2756   2756   2756   2756
    5       5125   5125   5125   5125   5125   5125   5125   5125   5125
    6       2235   2235   2235   2235   2235   2235   2235   2235   2235
    7       2941   2941   2941   2941   2941   2941   2941   2941   2941
    8       3152   3152   3152   3152   3152   3152   3152   3152   3152
    10      1214   1214   1214   1214   1214   1214   1214   1214   1214
    11     15547  15547  15547  15547  15547  15547  15547  15547  15547
10  0       9451   9451   9451   9451   9451   9451   9451   9451   9451
    1       4582   4582   4582   4582   4582   4582   4582   4582   4582
    2       1666   1666   1666   1666   1666   1666   1666   1666   1666
    3       4349   4349   4349   4349   4349   4349   4349   4349   4349
    4       5952   5952   5952   5952   5952   5952   5952   5952   5952
    5       3085   3085   3085   3085   3085   3085   3085   3085   3085
    6       1729   1729   1729   1729   1729   1729   1729   1729   1729
    7      22912  22912  22912  22912  22912  22912  22912  22912  22912
    8       3026   3026   3026   3026   3026   3026   3026   3026   3026
    9        631    631    631    631    631    631    631    631    631
    11     92369  92369  92369  92369  92369  92369  92369  92369  92369
11  0       4388   4388   4388   4388   4388   4388   4388   4388   4388
    1       2693   2693   2693   2693   2693   2693   2693   2693   2693
    2       1824   1824   1824   1824   1824   1824   1824   1824   1824
    3       1177   1177   1177   1177   1177   1177   1177   1177   1177
    4       3229   3229   3229   3229   3229   3229   3229   3229   3229
    5       3092   3092   3092   3092   3092   3092   3092   3092   3092
    6       3583   3583   3583   3583   3583   3583   3583   3583   3583
    7       8867   8867   8867   8867   8867   8867   8867   8867   8867
    8       6031   6031   6031   6031   6031   6031   6031   6031   6031
    9        308    308    308    308    308    308    308    308    308
    10     41592  41592  41592  41592  41592  41592  41592  41592  41592

              9      10     11
max max_2
0   1        783    783    783
    2       3308   3308   3308
    3       3129   3129   3129
    4       5718   5718   5718
    5        427    427    427
    6       3268   3268   3268
    7      22044  22044  22044
    8       3825   3825   3825
    9        153    153    153
    10      5579   5579   5579
    11      8381   8381   8381
1   0       7891   7891   7891
    2        135    135    135
    3      34523  34523  34523
    4        760    760    760
    5       2157   2157   2157
    6        813    813    813
    7       5813   5813   5813
    8       1174   1174   1174
    9        271    271    271
    10       702    702    702
    11     40445  40445  40445
2   0       5044   5044   5044
    1        785    785    785
    3        473    473    473
    4       1500   1500   1500
    5        574    574    574
    6       4413   4413   4413
    7       5820   5820   5820
    8       7770   7770   7770
...          ...    ...    ...
9   3      11727  11727  11727
    4       2756   2756   2756
    5       5125   5125   5125
    6       2235   2235   2235
    7       2941   2941   2941
    8       3152   3152   3152
    10      1214   1214   1214
    11     15547  15547  15547
10  0       9451   9451   9451
    1       4582   4582   4582
    2       1666   1666   1666
    3       4349   4349   4349
    4       5952   5952   5952
    5       3085   3085   3085
    6       1729   1729   1729
    7      22912  22912  22912
    8       3026   3026   3026
    9        631    631    631
    11     92369  92369  92369
11  0       4388   4388   4388
    1       2693   2693   2693
    2       1824   1824   1824
    3       1177   1177   1177
    4       3229   3229   3229
    5       3092   3092   3092
    6       3583   3583   3583
    7       8867   8867   8867
    8       6031   6031   6031
    9        308    308    308
    10     41592  41592  41592

[132 rows x 12 columns]

In [102]:
bask_tg_12['trans_key']=bask_tg_12.index
tag_bask=sqlContext.createDataFrame(bask_tg_12.loc[:,['trans_key','max']])

tag_bask.write.save('/user/garimaj/tag_bask', mode = 'overwrite')

tag_bask.show()